refactor

diff --git a/bobtest b/bobtest
--- a/bobtest
+++ b/bobtest
@@ -13,33 +13,39 @@ main() {
 	done
 }
 
+# fun: test_file SCRIPT[:FUNCTION]
 test_file() {
-	script="$1"
-	script_real_path=$(realpath "$script")
-	printf 'file %s:\n' "$script"
-	function_names=$(sed --silent --regexp-extended 's/^( *function)? *(test_\w+) *\( *\) *\{ *$/\2/pg' "$script_real_path")
-	for func in $function_names; do
-		printf '  function %s... ' "$func"
-		if ! sh -c "set -eu; . '$SHELDUCK_LIB'; . '$script_real_path' ; set -x; '$func'" > "$stdout_file" 2> "$stderr_file"; then
-			printf 'failure\n\n'
-			printf '\n\nSTDOUT WAS:\n%s\n'
-			cat "$stdout_file"
-			
- 			printf '\n\nSTDERR WAS:\n%s\n'
-			cat "$stderr_file"
-			
-			exit
-		fi
-		printf ' ok\n'
-	done
+	test_file="$1"
+	bobshell_split_first "$test_file" : test_file test_function || true
+
+	test_file_real_path=$(realpath "$test_file")
+	printf 'file %s:\n' "$test_file"
+	if [ -n "${test_function:-}" ]; then
+		test_function "$test_file_real_path" "$test_function"
+	else
+		all_test_functions=$(sed --silent --regexp-extended 's/^( *function)? *(test_\w+) *\( *\) *\{ *$/\2/pg' "$test_file_real_path")
+		for test_function in $all_test_functions; do
+			test_function "$test_file_real_path" "$test_function"
+		done
+	fi
 }
 
-
-shelduck_exec() {
-	shelduck_resolve "$1"
-
-
+# fun: test_function SCRIPT FUNCTION
+test_function() {
+	printf '  function %s... ' "$2"
+	if ! sh -c "set -eu; . '$SHELDUCK_LIB'; . '$1' ; set -x; '$2'" > "$stdout_file" 2> "$stderr_file"; then
+		printf 'failure\n\n'
+		printf '\n\nSTDOUT WAS:\n%s\n'
+		cat "$stdout_file"
+		
+		printf '\n\nSTDERR WAS:\n%s\n'
+		cat "$stderr_file"
+		
+		exit
+	fi
+	printf ' ok\n'
 }
+
 
 
 
@@ -47,6 +53,7 @@ test -r ./shelduck.sh && . ./shelduck.sh
 : "${SHELDUCK_BASE_URL:=file://./}"
 export SHELDUCK_BASE_URL
 shelduck import base.sh
+shelduck import string.sh
 
 
 main "$@"
